### ISSUE TITLE
Why a new API?

### ISSUE THREAD

**Issue by ibc** [alongubkin/phonertc#107]
Hi, just wondering: why do you provide a new API instead of implementing the [WebRTC API](http://www.w3.org/TR/webrtc/)? Mandating a new API means that a working JS browser application must be translated into the Cordova `phonertc` API.

What I expected from this project was a transparent implementation of the `RTCPeerConnection` interface and so on. What's the motivation for designing a new API?

If I miss something please let me know.

**Comment by ibc** [comment]
FYI: WebRTC full JavaScript API implemented in Cordova iOS: https://github.com/eface2face/cordova-plugin-iosrtc

Still missing the `video.src = URL.createObjectURL(stream)` stuff, but will be suddenly implemented in the next days.

**Comment by mark-veenstra** [comment]
nice work inaki

**Comment by ibc** [comment]
BTW, `video.src = URL.createObjectURL(stream)` implemented:

https://github.com/eface2face/cordova-plugin-iosrtc/blob/master/js/videoElementsHandler.js

**Comment by alongubkin** [comment]
Nice! This is way better than PhoneRTC.

**Comment by ibc** [comment]
I just can say thanks to PhoneRTC for more than just inspiration ;)
