### ISSUE TITLE
Please document data in sendMessage

### ISSUE THREAD

**Issue by ibc** [alongubkin/phonertc#111]
I'm 100% lost regarding what I should expect in the `data` object of the `sendMessage` event. Please, let me know which exact objects I should be ready to receive and I will make a PR documenting them.

AFAIK those are:
- `{ type:'offer', spd:SDP_STRING }`
- `{ type:'answer', spd:SDP_STRING }`
- `{ type:'candidate', candidate:CANDIDATE_STRING }`
  *\* Does CANDIDATE_STRING begins with "a=" and ends with "\r\n"? or does it use the old spec syntax?
  *\* Is there a `candidate:null` to signal end of candidates?

In `src/android/com/dooble/phonertc/Session.java` I also find:

```
public void onIceGatheringChange(IceGatheringState arg0) {
   json.put("type", "IceGatheringChange");
```

which seems to be used in [onsip-cordova](https://github.com/onsip/onsip-cordova/blob/master/www/index.js#L145), but it seems not to exist under the `src/ios/` folder.

Is that part of the API? just in Android?

Please, clarify this. Otherwise it is unfeasible to use phonertc for a purpose different than communicating two mobiles both using a `phonertc` based app.

**Comment by jesusprubio** [comment]
Only to confirm, we have to assume that this project is not going to implement the standard, isn't it? :(

**Comment by ibc** [comment]
@poshetz FYI, WebRTC full JavaScript API implemented in Cordova iOS: https://github.com/eface2face/cordova-plugin-iosrtc

**Comment by poshetz** [comment]
woa! @ibc  FINALLY thanks
