### ISSUE TITLE
App crashes in iOS at launch

### ISSUE THREAD

**Issue by swells808** [alongubkin/phonertc#113]
I downloaded and compiled the latest build using Xcode 6.1 and loaded it onto an iPhone 5s and iPad mini to test. Both instances crash upon load.

After reviewing the error reports I found this to be the crash issue
<code>
Dyld Error Message:
  Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /private/var/mobile/Containers/Bundle/Application/0BD865E2-AD0C-4277-B3E7-5E5FB863EBCA/HelloCordova.app/HelloCordova
  Reason: image not found
  Dyld Version: 353.6
</code>

After some searching I came across this link https://www.airsignapp.com/ios-apps-using-swift-crash-when-signed-with-inhouse-certificate/

Which outlines this as a certificate issue and asks a user to regenerate certificates and a new code signing identity. I did this and the issue persists. Any one have any ideas?

Is there a non swift version of the code so I can try in an older version of Xcode?

**Comment by ShongSu** [comment]
same errors
