### ISSUE TITLE
Keep Receiving Build Errors in IOS

### ISSUE THREAD

**Issue by windht** [alongubkin/phonertc#127]
I use Ionic CLI.
Everything Worked fine for the first build following your instructions. 
But the second time to build (build again),will cause the following error.

_get_field_types_Session in Session.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

So I have to remove the platform and add again. And I have to go over all the setting one by one again.
Are there any other ways? Or what I am doing wrong?

**Comment by NayRia** [comment]
This is actually OK, you need to cordova/ionic build ios and then run the app from Xcode on a real iOS device.

**Comment by windht** [comment]
Thanks @NayRia !
I just happended to have some other issue troubling "cordova update" where I need to rebuild the project. It is okay for me to use "cordova prepare ios" now~Please close this issue.
