### ISSUE TITLE
how to make audio call?

### ISSUE THREAD

**Issue by makersu** [alongubkin/phonertc#149]
Hi:
I'd like to make an audio call, and i think it might be:
1.create AudioGLView like VideoGLView? 
2.using VideoConfig, set config.isVideoStreamEnabled() = false?
Any suggestion?
Thank you very much.

**Comment by alongubkin** [comment]
https://github.com/alongubkin/phonertc/commit/9bec09c0558844ff5fbed6ef0db89bb9f67e2eba
