### ISSUE TITLE
android - ReferenceError: phonertc is not defined

### ISSUE THREAD

**Issue by dbroadhurst** [alongubkin/phonertc#158]
I get ReferenceError: phonertc is not defined error when running

var session = new phonertc.Session(config);

I've checked the manifest and the build output and I can see the plugin.

I'm using Cordova 5.1.1

I'm successfully using other plugins.

**Comment by ajaychaudhary77** [comment]
Hi i am getting the same message what was the issue

**Comment by Jenjen1324** [comment]
In honor of: https://xkcd.com/979/
See this thread: http://stackoverflow.com/questions/38718223/phonertc-is-not-defined-cordova-phonertc-on-browser

Basically: change `phonertc` to `cordova.plugins.phonertc`
