### ISSUE TITLE
Swift files can't be compiled in Xcode

### ISSUE THREAD

**Issue by mrsunlin** [alongubkin/phonertc#167]
It seems swift 1.2 is deprecated

**Comment by marcossandrini** [comment]
I'm having issues with compiling on XCode 7.0 (7A220) as well. 

First it asks to update the code (if I don't update it just fails with numerous errors). Then after updating the code it gives 4 errors, about "?" or "!" that should be put on places. After putting either ? or ! on those places, it fails again, now with a bunch of errors like "_OBJC_CLASS_$_RTCAudioTrack", referenced from:     l_get_field_types_PhoneRTCPlugin in PhoneRTCPlugin.o"

**Comment by zihzo** [comment]
Same here any luck finding a fix?

**Comment by alongubkin** [comment]
Working on a fix

**Comment by alongubkin** [comment]
Not a fix, but a workaround for now:

1. For all the "?"/"!" errors, just add a "!".
2. In build settings, disable "Enable Bitcode"

I'll push a real fix, including a better port to Swift 2.0 soon.

**Comment by derwaldgeist** [comment]
Any updates on this? I can't get this runnning, as it has some more problems than just the ! parts.

**Comment by seraphpl** [comment]
Same here.

**Comment by gabri15** [comment]
Same here too!!

**Comment by derwaldgeist** [comment]
It seems as if this project is not being maintained any more. Which is quite sad, since I really liked the idea to have some OpenTok-independent implementation for WebRTC.

**Comment by Rubinhuang9239** [comment]
Got a same issue...

**Comment by ethanzzx** [comment]
Same here too!

**Comment by bart-jansen** [comment]
same here.. @alongubkin when would this be fixed? Is there a workaround yet for the println/Extra argument(`error`)/`params`, `join` which is unavailable etc. yet?

**Comment by alongubkin** [comment]
https://github.com/alongubkin/phonertc/commit/ac383496a247ded4444169b8ef13a813f9baf8fa

**Comment by derwaldgeist** [comment]
Wow, thanks for fixing this!
