### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by derwaldgeist** [alongubkin/phonertc#173]
I really love the idea of this project and would like to use the code. But as both the Android and iOS versions seem to be broken at the moment (with some issues pending for a while), I'm wondering if this repo is still maintained and will be in the nearer future?

**Comment by alongubkin** [comment]
Both Android and iOS versions are working. This repo is currently maintained minimally (only critical bugfixes, no new features).

**Comment by alongubkin** [comment]
Both Android and iOS versions are working. This repo is currently maintained minimally (only critical bugfixes, no new features).

**Comment by derwaldgeist** [comment]
Ok. Thanks for the info. But I did not get any one of these versions to work. So if the repo is only maintained minimally, we cannot expect that this will be developed further, right?
