### ISSUE TITLE
Issue: Video initialization exception

### ISSUE THREAD

**Issue by weahoo** [alongubkin/phonertc#197]
I am using Nexus 7 with the latest Android 6.0.1 to run the demo, unfortunately I met the following issue:

> 04-28 17:18:32.323: E/WEBRTC-JC(27537): Failed to open Camera 1, Facing front, Orientation 270, skipping
> 04-28 17:18:32.323: E/WEBRTC-JC(27537): java.lang.RuntimeException: Fail to connect to camera service

> 04-28 17:18:32.323: E/WEBRTC-JC(27537): 	at org.webrtc.videoengine.VideoCaptureDeviceInfoAndroid.getDeviceInfo(VideoCaptureDeviceInfoAndroid.java:56)
> 04-28 17:18:32.460: E/AndroidRuntime(27537): java.lang.RuntimeException: Failed to open capturer
> 04-28 17:18:32.460: E/AndroidRuntime(27537): 	at com.dooble.phonertc.PhoneRTCPlugin.getVideoCapturer(PhoneRTCPlugin.java:291)
> 04-28 17:18:32.460: E/AndroidRuntime(27537): 	at com.dooble.phonertc.PhoneRTCPlugin.initializeLocalVideoTrack(PhoneRTCPlugin.java:221)
> 04-28 17:18:32.460: E/AndroidRuntime(27537): 	at com.dooble.phonertc.PhoneRTCPlugin$6.run(PhoneRTCPlugin.java:189)

May I know this issue is due to upgrade of the system and the webrtc.VideoCamera didn't work any more, or something I am missing?
Shell I switch to Crosswalk to walkaround this issue? Thanks

**Comment by Mgonand** [comment]
I compiled de latest WebRTC binaries and did some fixes to be able to get a videocall in latest cordova Android versions. You can check it out in my fork https://github.com/Mgonand/phonertc 

That works for me on latest versions of Android and iOS, I don't know if it works in older versions. Use it at your own risk.

**Comment by alongubkin** [comment]
https://github.com/alongubkin/phonertc/commit/899f604482d407fcad924bf6ce558418fefb4ca7
