### ISSUE TITLE
Build a demo app

### ISSUE THREAD

**Issue by alongubkin** [alongubkin/phonertc#35]
PhoneRTC should have a demo app built with Cordova (and probably Ionic) to show its functionality. It should also include a basic signaling server build with Node.js/Socket.IO.

**Comment by buddy666** [comment]
Phonegap Build changed their limitations: http://phonegap.com/blog/2014/12/09/phonegap-build-new-features/
Do you think it is now possible to add your plugin to PG Build?

Benny
