### ISSUE TITLE
iOS didSetSessionDescriptionWithError

### ISSUE THREAD

**Issue by dorinsimina** [alongubkin/phonertc#40]
For the iOS implementation I get the following error in didSetSessionDescriptionWithError:

Error Domain=RTCSDPError Code=-1 "The operation couldn’t be completed. (RTCSDPError error -1.)" UserInfo=0x1cb6a670 {error=Failed to set remote answer sdp: Called in wrong state: STATE_RECEIVEDACCEPT}

This issue affects the video streaming to be paused for several seconds and start again to work for a short period and so on. Does anyone know what might be the problem?

**Comment by chetanbnaik** [comment]
Hi, I am trying to establish a webrtc call between a modified peerjs on browser and phonertc app on android. I have set up a socket.io based signaling server and am communicating to a modified peerjs. 

My goal is to be able to make a seemless app where the endpoint could be peerjs or phonertc.

Usage of Peerjs suggests directly making an offer without waiting for the callee to take any specific action.

please explain the reason why is it needed to call with "isInitiator:false" before calling "isInitiator:true"? is there any way to remove this dependency? I can change the flow of events on the peerjs side, but would like to understand why is it so?
