### ISSUE TITLE
Avoid TURN server

### ISSUE THREAD

**Issue by nicola** [alongubkin/phonertc#56]
Is there any way to avoid the TURN server and do instead signaling with something like.. socket.io ?

**Comment by Jenjen1324** [comment]
Why is TURN required when it's not in the WebRTC spec? WebRTC is p2p and tries a direct connection first using a STUN server if necessary/available. Why can't we specify and use STUN instead/along TURN in this plugin?

**Comment by murugan-pandian** [comment]
@Jenjen1324  WebRTC p2p (means IP-2-IP) STUN-Only convert your private IP into public IP ,Some case you can't able to make call between two IP's(p2p) because of firewall issue so your call may fails,To avoid this problem we are using TURN server

**Comment by Jenjen1324** [comment]
@murugan-pandian That still doesn't mean that you are required to provide a TURN server as the author of the plugin states. It should be an optional parameter.

I've anyways opted to use the RTC API from webkit along with [iosrtc](https://github.com/eface2face/cordova-plugin-iosrtc) as the WebView supports it now, even though that will break backwards-compatibility to versions below Android 4.4

**Comment by xLama** [comment]
You don´t need it in local network.
