### ISSUE TITLE
getUsermedia and video streaming

### ISSUE THREAD

**Issue by nicola** [alongubkin/phonertc#58]
Safari does not implement getUsermedia, how can I get my live camera and put that as src in a video?

```
localVideo: document.getElementById('localVideo')
```

Will this create a getUsermedia stream or I have to do so?

**Comment by VinothRathinaKumar** [comment]
Hi, I am trying to establish connection between my android devices. But, cant able to send or receive any media stream from my android device(device camera is not opening by default). 

I have built an Ionic App and included PhoneRTC plugin. It works well with browser(added browser as platform in ionic) but in android device it fails. But, the server connection is established. 

Pls help me in finding where i went wrong
