### ISSUE TITLE
PhoneRTC with SIP.js

### ISSUE THREAD

**Issue by lylepratt** [alongubkin/phonertc#7]
Hi! Thanks for the awesome work on this plugin.

I'm looking for a solution to use SIP.js with with iOS devices. Could PhoneRTC help me with that? Is there anything preventing those libraries from working in conjunction with PhoneRTC?

Edit: @joseph-onsip I noticed that you have forked this repo and the SIP.js is an OnSIP project. Can you comment on this?

**Comment by andresfmg** [comment]
sorry, anybody find someway to integrate phonertc with sip on phonegap build ??
thanks a lot any help
