### ISSUE TITLE
Incoming call - bring the app to the foreground

### ISSUE THREAD

**Issue by drakula84** [alongubkin/phonertc#72]
More of a generic type question in hybrid/cordova application development but it is quite applicable for almost any application that is going to use this plugin. 

When the application is running in the background or when user is using another application, how can you bring the application to the foreground if there is an incoming call? 

I think there is two cases to deal with here:
1. The application is still running in the background and receiving the incoming call through signalling, i.e. socket.io as in the demo client app. How can you make the application top window in that case?
2. The application is not running, i.e. OS killed the process. In this case, I think, notification plugins are close to the solution. They use GCM/APN to deliver the message to the device and start the application. However, I think user needs to click the notification first to land into the application rather than directly displaying the call page by launching the application and bringing it to foreground without user clicking the notification.

Any thoughts?

**Comment by sathyaincampus** [comment]
Hi,

   I am facing the same kind of issue.

@drakula84  / @alongubkin :+1: 

1. can you please let me know what is the best way to bring up the viber / whatsapp calling kind of experience? I am using ionic to do stuff though. I would need it for both android and ios. 

2. Also if the app is not even open, how does the caller communicate to the signaling server and how will the app be invoked at the receiver end? Can you please throw some light?

Regards,
Sathya

**Comment by nkhlsharma26** [comment]
Hi
I know I am to answer this and hope that you have figured the solution, but for those who stumble upon this link searching the answer, please look at push-kit notification services. Apple has special notification service for VOIP applications that starts the app without waiting for user response.
