### ISSUE TITLE
ld: symbol(s) not found for architecture armv7

### ISSUE THREAD

**Issue by oleg-ria** [alongubkin/phonertc#80]
Hey,
trying to run my app based on the demo. "ionic run ios" gave me error
 "_glDisable", referenced from:
      +[RTCOpenGLVideoRenderer initialize] in libjingle_peerconnection_objc.a(libjingle_peerconnection_objc.RTCOpenGLVideoRenderer.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

*\* BUILD FAILED **

The following build commands failed:
    Ld build/[myApp].build/Debug-iphoneos/[myApp].build/Objects-normal/armv7/[myApp] normal armv7
(1 failure)
Error: /[path to my app]/platforms/ios/cordova/run: Command failed with exit code 65

**Comment by AhsanAyaz** [comment]
+1
Has this been resolved by anyone or did anyone found a solution that works? I'm facing the same issue. The same error.
