### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by cremfert** [alongubkin/phonertc#83]
Dear all,

I'm trying to set up a little prototype for a browser application. As you mention browser support, is it enough to include the src/browser/PhoneRTCProxy.js and then use the same code as described in the wiki to get PhoneRTC up and running in a browser?

Thanks and best regards,
Chris

**Comment by AmirAly** [comment]
@inspiraluna  can i use it in a browser without cordova ?, im using phonegab build so i don't wont to use cordova cli engine

**Comment by inspiraluna** [comment]
Works in chrome and firebox. Plugins for safari and ie.

**Comment by AmirAly** [comment]
@inspiraluna  i know , the question is , i need to integrate it without cordova in a web browser, what file should i include and how

**Comment by niyando** [comment]
@AmirAly were you able to make it work in safari browser without cordova?

**Comment by AmirAly** [comment]
@niyando  switched to only javascript with Crosswalk
