### ISSUE TITLE
Building ios failed.

### ISSUE THREAD

**Issue by crapthings** [alongubkin/phonertc#90]
3 issues

/Users/zhanghong/dev/newapp/.meteor/local/cordova-build/platforms/ios/newapp/Plugins/com.dooble.phonertc/Session.swift:47:24: 'URLWithString' is unavailable: use object construction 'NSURL(string:)'

/Users/zhanghong/dev/newapp/.meteor/local/cordova-build/platforms/ios/newapp/Plugins/com.dooble.phonertc/Session.swift:52:24: 'URLWithString' is unavailable: use object construction 'NSURL(string:)'

/Users/zhanghong/dev/newapp/.meteor/local/cordova-build/platforms/ios/newapp/Plugins/com.dooble.phonertc/Session.swift:200:48: 'regularExpressionWithPattern(_:options:error:)' is unavailable: use object construction 'NSRegularExpression(pattern:options:error:)'

**Comment by manur** [comment]
In case anyone else finds this,

Ensure that your build target is an actual iPhone or iPad running on the arm7 architecture. The iPhone and iPad simulators are not emulators, and only run on i386. The compiled RTC libraries for ios have been built for arm7.

**Comment by bassemBMI** [comment]
Hi there,
I followed all instructions or iOS but I have 25 errors most of theme are related to the "try" statement:

let json = (try! NSJSONSerialization.JSONObjectWithData(message,
            options: NSJSONReadingOptions.MutableLeaves)) as! NSDictionary
==> Expected ',' separator
==> Use of unresolved identifier 'try'

do {
            data = try NSJSONSerialization.dataWithJSONObject(json,
                        options: NSJSONWritingOptions())
        } catch let error as NSError {
            jsonError = error
            data = nil
        }

==> Consecutive statements on a line must be separated by ';'
 
Something wrong in my config ?

Thx
