### ISSUE TITLE
Android choppy audio

### ISSUE THREAD

**Issue by cesterlizi** [alongubkin/phonertc#99]
Hi
I am testing the demo client & server and the audio coming from android sounds choppy.
Android 4.4.2 Samsun S4   --------> PC Browser : choppy audio, Video OK
PC Browser  -------> Android 4.4.2 Samsun S4  : Audio OK, Video OK
PC to PC works fine, I haven't tested on iOS yet

Is anyone having the same problem?

I've captured the RTP stream from the android and is not streaming constant 

Carlos

**Comment by alaghusun60** [comment]
@plexorama @alongubkin @cesterlizi   in android audio working. Browser audio not working. Whether this is bandwith issue or other than something
